// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getServerProfiles() : Promise<Result<ServerProfile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveServerProfile(profile: ServerProfile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_server_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateServerProfile(sourceId: string, profile: ServerProfile) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_server_profile", { sourceId, profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteServerProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_server_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnection(profileId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testProfileConnection(profile: ServerProfile, fallbackPasswordProfileId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_profile_connection", { profile, fallbackPasswordProfileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatabases(profileId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_databases", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runMaintenance(profileId: string, databases: string[], options: MaintenanceOptions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_maintenance", { profileId, databases, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseMaintenance(profileId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_maintenance", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeMaintenance(profileId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_maintenance", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipDatabase(profileId: string, dbName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_database", { profileId, dbName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopMaintenance(profileId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_maintenance", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRunHistory(profileId: string | null, limit: number | null) : Promise<Result<RunRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run_history", { profileId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearRunHistory(profileId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_run_history", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthType = "sqlServer"
export type DatabaseResult = { database_name: string; success: boolean; indexes_processed: number; indexes_rebuilt: number; indexes_reorganized: number; indexes_skipped: number; total_duration_secs: number; errors: string[]; critical_failure: boolean; manually_skipped: boolean; interrupted?: boolean; index_results?: IndexResult[] }
export type Environment = "production" | "staging" | "uat" | "development" | "other"
export type IndexResult = { schema_name: string; table_name: string; index_name: string; fragmentation_percent: number; page_count: number; action: MaintenanceAction; success: boolean; duration_secs: number; retry_attempts: number; error: string | null }
export type MaintenanceAction = "REBUILD" | "REORGANIZE" | "SKIP"
export type MaintenanceOptions = { rebuild_online?: boolean; free_proc_cache?: boolean; rebuild_threshold?: number; reorganize_threshold?: number; retry_max_attempts?: number; retry_base_delay_ms?: number; retry_max_delay_ms?: number; connection_timeout_ms?: number; request_timeout_ms?: number; parallel_databases?: boolean; max_parallel_databases?: number }
export type RunRecord = { id: number; profile_id: string; profile_name: string; server: string; started_at: string; finished_at: string; databases_processed: number; databases_failed: number; databases_skipped: number; total_indexes_rebuilt: number; total_indexes_reorganized: number; total_indexes_skipped: number; total_duration_secs: number; database_results: DatabaseResult[] }
export type ServerProfile = { id: string; name: string; server: string; port: number; auth_type?: AuthType; username: string; password: string; encrypt: boolean; trust_server_certificate: boolean; environment?: Environment }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
